### ISSUE TITLE
npm start -r fails with Failed to load registration file Error

### ISSUE THREAD

**Issue by ajkessel** [Sorunome/mx-puppet-instagram#31]
Following the non-Docker [installation directions](https://github.com/Sorunome/mx-puppet-instagram/blob/master/README.md) exactly on a standard Ubuntu box fails when attempting to generate the registration file. (Path below for directory with github clone/build has been simplified to /path/bridge):

npm start -r

 mx-puppet-instagram@0.0.0 start /path/bridge/instagram
 npm run-script build && node ./build/index.js

 mx-puppet-instagram@0.0.0 build /path/bridge/instagram
 tsc

Nov-18 19:40:24.758 [PuppetBridge] error: Failed to load registration file Error: ENOENT: no such file or directory, open 'instagram-registration.yaml'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at PuppetBridge.readConfig (/path/bridge/instagram/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:129:49)
    at PuppetBridge.<anonymous> (/path/bridge/instagram/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:154:18)
    at Generator.next (<anonymous>)
    at /path/bridge/instagram/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/path/bridge/instagram/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:16:12)
    at PuppetBridge.init (/path/bridge/instagram/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:153:16)
    at /path/bridge/instagram/build/index.js:74:22
    at Generator.next (<anonymous>)
    at /path/bridge/instagram/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/path/bridge/instagram/build/index.js:4:12)
    at run (/path/bridge/instagram/build/index.js:73:12)
    at Object.<anonymous> (/path/bridge/instagram/build/index.js:203:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'instagram-registration.yaml'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mx-puppet-instagram@0.0.0 start: npm run-script build && node ./build/index.js
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the mx-puppet-instagram@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thekumi** [comment]
I was seeing the same issue, but figured it out by comparing the instructions here to the instructions at https://github.com/Sorunome/mx-puppet-slack - the correct command to generate the registration file is `npm run start -- -r`
