### ISSUE TITLE
Config.yaml?

### ISSUE THREAD

**Issue by DoM1niC** [Sorunome/mx-puppet-instagram#6]
I wanne setup this Bridge but I missed the `config.yaml` the buildung was success and so on but it seems the config is currently not included ?

**Comment by Sorunome** [comment]
There's one in the bridge library here https://github.com/Sorunome/mx-puppet-bridge/blob/master/sample.config.yaml that should work

**Comment by DoM1niC** [comment]
OMG THX!!! I will try it nice work :) btw

**Comment by DoM1niC** [comment]
I tried it but I got this error :(

```
Mar-18 11:54:13.263 [PuppetBridge] error: Failed to load config file TypeError:                                                                                                                                                              Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Config.applyConfig (/home/projects/python/mx-puppet-instagram/build/node_                                                                                                                                                             modules/mx-puppet-bridge/lib/src/config.js:31:16)
    at Object.keys.forEach (/home/projects/python/mx-puppet-instagram/build/node                                                                                                                                                             _modules/mx-puppet-bridge/lib/src/config.js:33:22)
    at Array.forEach (<anonymous>)
    at Config.applyConfig (/home/projects/python/mx-puppet-instagram/build/node_                                                                                                                                                             modules/mx-puppet-bridge/lib/src/config.js:31:32)
    at PuppetBridge.readConfig (/home/projects/python/mx-puppet-instagram/build/                                                                                                                                                             node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:82:25)
    at PuppetBridge.<anonymous> (/home/projects/python/mx-puppet-instagram/build                                                                                                                                                             /node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:101:18)
    at Generator.next (<anonymous>)
    at /home/projects/python/mx-puppet-instagram/build/node_modules/mx-puppet-br                                                                                                                                                             idge/lib/src/puppetbridge.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/projects/python/mx-puppet-instagram/build/node_modules/m                                                                                                                                                             x-puppet-bridge/lib/src/puppetbridge.js:16:12)
    at PuppetBridge.init (/home/projects/python/mx-puppet-instagram/build/node_m                                                                                                                                                             odules/mx-puppet-bridge/lib/src/puppetbridge.js:100:16)
    at /home/projects/python/mx-puppet-instagram/build/index.js:74:22
    at Generator.next (<anonymous>)
    at /home/projects/python/mx-puppet-instagram/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/projects/python/mx-puppet-instagram/build/index.js:4:12)
    at run (/home/projects/python/mx-puppet-instagram/build/index.js:73:12)
    at Object.<anonymous> (/home/projects/python/mx-puppet-instagram/build/index                                                                                                                                                             .js:203:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
python@webapps:~/mx-puppet-instagram/build$
```

**Comment by Sorunome** [comment]
try soemthing more minimalistic like

```
bridge:
  port: 8435
  domain: localhost
  homeserverUrl: http://localhost:8008
logging:
  console: info
provisioning:
  whitelist:
   - ".*"
```

maybe?

**Comment by DoM1niC** [comment]
> try soemthing more minimalistic like
> 
> ```
> bridge:
>   port: 8435
>   domain: localhost
>   homeserverUrl: http://localhost:8008
> logging:
>   console: info
> provisioning:
>   whitelist:
>    - ".*"
> ```
> 
> maybe?
> 
> EDIT: adjust localhost to your stuffs, ofc. And the whitelist

yeah I got the registration file now and will try it what I have to do if I run the bridge to sign my insta account in?

**Comment by DoM1niC** [comment]
now I need to know how I use your pupped I already use Mautrix WA / FB Bridge, but here I lost so much instructions because this seems fully in development :(

**Comment by Sorunome** [comment]
You create a room and invite `@_instagrampuppet_bot:yourserver.com`. Once it joins that should be your status room. You can type `help` to list all available commands. what you are looking for is `link <username> <password>`

While this bridge sadly lacks documentation it should be fully functional already

**Comment by DoM1niC** [comment]
> You create a room and invite `@_instagrampuppet_bot:yourserver.com`. Once it joins that should be your status room. You can type `help` to list all available commands. what you are looking for is `link <username> <password>`
> 
> While this bridge sadly lacks documentation it should be fully functional already

I try it now 

Whats about this error after 2nd start the pupped ?
`[bot-sdk-MatrixLiteClient] error: (REQ-1) { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' }`

**Comment by DoM1niC** [comment]
its still in invitation process here :( 
![image](https://user-images.githubusercontent.com/1436958/76957147-9b5cc780-6915-11ea-9420-e73bf31a8eba.png)

**Comment by Sorunome** [comment]
> Whats about this error after 2nd start the pupped ?
[bot-sdk-MatrixLiteClient] error: (REQ-1) { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' }

That error is safe to ignore

**Comment by Sorunome** [comment]
> its still in invitation process here :(
> ![image](https://user-images.githubusercontent.com/1436958/76957147-9b5cc780-6915-11ea-9420-e73bf31a8eba.png)

Sounds like synapse isn't communicating with the appservice. Would you mind joining #mx-puppet-bridge:sorunome.de for easier debugging?
